version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data  
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.0
    ports:
      - "5000:5000"
      - "9600:9600"
    configs:
      - source: pipelines_config
        target: /usr/share/logstash/config/pipelines.yml
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: apache_log_pipeline
        target: /usr/share/logstash/pipeline/apache_log.conf
      - source: elasticsearch_to_csv_pipeline
        target: /usr/share/logstash/pipeline/elasticsearch_to_csv.conf
      - source: logstash_network_traffic_pipeline
        target: /usr/share/logstash/pipeline/logstash_network_traffic_data.conf
      - source: logstash_products_pipeline
        target: /usr/share/logstash/pipeline/logstash_products.conf
      - source: collectd_pipeline
        target: /usr/share/logstash/pipeline/collectd.conf
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf   
    volumes:
      - /home/vagrant/logstash/data:/usr/share/logstash/data                                    
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.logstash == yes

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - /home/vagrant/kibana/data:/usr/share/kibana/data
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.kibana == yes

configs:

  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./logstash/config/logstash.yml
  pipelines_config:
    file: ./logstash/config/pipelines.yml
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  apache_log_pipeline:
    file: ./logstash/pipeline/apache_log.conf
  elasticsearch_to_csv_pipeline:
    file: ./logstash/pipeline/elasticsearch_to_csv.conf
  logstash_network_traffic_pipeline:
    file: ./logstash/pipeline/logstash_network_traffic_data.conf
  logstash_products_pipeline:
    file: ./logstash/pipeline/logstash_products.conf
  collectd_pipeline:
    file: ./logstash/pipeline/collectd.conf
  kibana_config:
    file: ./kibana/config/kibana.yml    

networks:
  elk:
    driver: overlay